engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.md"
exclude_paths:
- test/
- node_modules/
- web/
