branches:
  except:
  - gh-pages
os: linux
dist: trusty
git:
  depth: 12
  submodules: false
cache:
  directories:
  - node_modules
node_js:
- '11'
language: node_js
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: d2WEDy5mjKV5bxTXW5tJiue+Nr/8erp4Bb/jw0MP0d6/9AEXcm5AyiQ662Ia9eiqEBM7cUquAMgiTtsbLkJb7yAHx/I6FuMfPCzdUKkR+2LAjDlDkCUkZC6wwXgKGpCPOFoSyIDBOl5DyHsty1tiw2jNbB+O+UjeFpmSdMehlYuu4ihCMqlqzq+t/PpnwsOnGPeQ286sSYfCA6cyfH9KC25Mx9lJntTaUL+MWFnLf/rWtfVZvJwDiDdDFW7jVYE31mp1gRMwv+f6Hdy8nfbI73GW0DeEdZYdAGfk8/0BBfKRRdrD30HCKx+RnDgiqxAQMvGC/6hvd7UuqgDTn62pN4rwGhjX1myJJnleS3kVtT18yiJCj4ILczED/P+vEbiOmGjsCqB+Adaq2CAL3cZVH8wGyLwLIsuADsK+UOrynlEvGX1QEQ/sQiGvyChQJYGe+N2597L1uwpnPfVXtpG0hankeiq+pqXJhFXWWrilSove2ggtL+2fMJZmqf46h4aIUUsfD+p+OFwIQB/y83EjBF0TwT3i6p6J3EClGf8u+FD/P6JwVwonj7IaS7lwtlTkpepf7/D3cCDhiu6+R3KAVVYVEWk+Xy0qTN5XexaRuRlGe1EwHdtjtUdcKk5I5NVzKe0HDjnVffKqg00Tz5FOPmrP/JWbhSSlKggW9ybT6XE=
