branches:
  except:
  - gh-pages
os: linux
git:
  depth: 12
  submodules: false
cache:
  directories:
  - node_modules
node_js:
- '16'
language: node_js
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli uglify-es@latest
