branches:
  except:
  - gh-pages
sudo: false
language: node_js
node_js:
- '7'
- '8'
before_script:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: gzy4bTdXi0W+JO7j9HecezXE0nC6LtoaXnVJbI8/4saZrFwqDmdn82Pubgdjpiv2WzbD3P35xlrTeVorq0HTuPPCNYMAsWLnhtb0V3FiUdb67O3nptoJQdgH+erSaSrzkYCfsGI5nFah8toVq3iiVRoU8GakL6S9MBCnzqWpsk8=
