branches:
  except:
  - gh-pages
os: linux
git:
  depth: 12
  submodules: false
cache:
  directories:
  - node_modules
node_js:
- '14'
- '15'
language: node_js
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli uglify-es@latest
notifications:
  slack:
    secure: U1awsxwBz9eLq+RzTBpizvHiJ3OdOlTEpstZePhjjte2Qd1L5DuQqVrbyxwdDGzJ88EaevACa5zKAy4hI3xhDW7Mx269h7DxmVESdJEwhkb+5YMHM11WgZC9Vg3Yru2wUIbibboNrCFB2oEGW03yd4VQi+wjoxr5dhL6HAizL2k=
