---
root: true

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    globalReturn: false
    impliedStrict: true
    jsx: false
    modules: false
  ecmaVersion: 6
  sourceType: script

plugins:
- json
- no-unsanitized
- security
- xss

# yamllint disable-line rule:line-length
extends: [eslint:recommended, plugin:json/recommended, plugin:security/recommended]

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  for-direction: "error"
  no-await-in-loop: "error"
  no-inner-declarations: ["error", functions]
  no-prototype-builtins: "error"
  no-template-curly-in-string: "error"
  no-unsafe-negation: "error"

  # Best Practices
  accessor-pairs: "error"
  array-callback-return: "error"
  block-scoped-var: "error"
  class-methods-use-this: "error"
  complexity: ["error", 28]
  consistent-return: "error"
  curly: "error"
  default-case: "error"
  guard-for-in: "error"
  no-alert: "off"
  no-caller: "error"
  no-div-regex: "error"
  no-else-return: "error"
  no-empty-function: "error"
  no-eq-null: "error"
  no-eval: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-extra-label: "error"
  no-implicit-coercion: "error"
  no-implicit-globals: "off"
  no-implied-eval: "error"
  no-invalid-this: "off"
  no-iterator: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-loop-func: "error"
  no-magic-numbers: "off"
  no-multi-str: "error"
  no-new-func: "error"
  no-new-wrappers: "error"
  no-new: "error"
  no-octal-escape: "error"
  no-param-reassign: "error"
  no-proto: "error"
  no-restricted-properties: "error"
  no-return-assign: "off"
  no-script-url: "off"
  no-self-compare: "error"
  no-sequences: "error"
  no-throw-literal: "warn"
  no-unmodified-loop-condition: "error"
  no-unused-expressions: "error"
  no-useless-call: "error"
  no-useless-concat: "error"
  no-useless-escape: "off"
  no-useless-return: "error"
  no-void: "off"
  no-warning-comments: "error"
  no-with: "error"
  prefer-promise-reject-errors: "error"
  radix: "error"
  require-await: "error"
  vars-on-top: "error"
  yoda: "off"

  # Variables
  init-declarations: "error"
  no-label-var: "error"
  no-restricted-globals: "error"
  no-shadow-restricted-names: "error"
  no-shadow: "error"
  no-undef-init: "error"
  no-undefined: "error"
  no-use-before-define: "error"

  # Stylistic Issues
  consistent-this: "error"
  func-name-matching: "error"
  id-denylist: "error"
  id-match: "error"
  line-comment-position: "error"
  max-depth: ["error", 5]
  # yamllint disable-line rule:line-length
  max-lines: ["error", {"max": 172, "skipBlankLines": true, "skipComments": true}]
  max-nested-callbacks: "error"
  max-params: ["error", 5]
  max-statements: ["error", 50]
  new-cap: "error"
  no-array-constructor: "error"
  no-bitwise: "off"
  no-continue: "error"
  no-inline-comments: "error"
  no-inline-config: "off"
  no-lonely-if: "error"
  no-negated-condition: "error"
  no-nested-ternary: "error"
  no-plusplus: "error"
  no-restricted-syntax: "error"
  no-ternary: "off"
  no-underscore-dangle: "error"
  no-unneeded-ternary: "error"
  one-var: "off"
  operator-assignment: "error"
  sort-keys: "error"
  sort-vars: "error"
  unicode-bom: "error"

  # ECMAScript 6
  arrow-body-style: "error"
  no-duplicate-imports: "error"
  no-restricted-imports: "error"
  no-useless-computed-key: "error"
  no-useless-constructor: "error"
  no-useless-rename: "error"
  no-var: "error"
  object-shorthand: "error"
  prefer-arrow-callback: "error"
  prefer-const: "warn"
  prefer-destructuring: "error"
  prefer-numeric-literals: "error"
  prefer-rest-params: "error"
  prefer-spread: "error"
  prefer-template: "off"
  sort-imports: "error"
  symbol-description: "error"

  # no-unsanitized - https://github.com/mozilla/eslint-plugin-no-unsanitized
  no-unsanitized/method: "error"
  no-unsanitized/property: "error"

  # security - https://github.com/nodesecurity/eslint-plugin-security
  security/detect-non-literal-regexp: "off"

  # xss - https://github.com/Rantanen/eslint-plugin-xss
  xss/no-location-href-assign: "off"
  xss/no-mixed-html: "error"
